/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 * Source: design-tokens/tokens.json
 * Regenerate: node scripts/generate-tokens.mjs
 */

export const THEMES = [
  'light',
  'dark',
  'high-contrast',
] as const;

export type Theme = (typeof THEMES)[number];

/** CSS custom property names, for programmatic access. */
export const tokenVars = {
  "primitiveColorBlue50": '--primitive-color-blue-50',
  "primitiveColorBlue100": '--primitive-color-blue-100',
  "primitiveColorBlue400": '--primitive-color-blue-400',
  "primitiveColorBlue500": '--primitive-color-blue-500',
  "primitiveColorBlue600": '--primitive-color-blue-600',
  "primitiveColorBlue700": '--primitive-color-blue-700',
  "primitiveColorBlue900": '--primitive-color-blue-900',
  "primitiveColorGray50": '--primitive-color-gray-50',
  "primitiveColorGray100": '--primitive-color-gray-100',
  "primitiveColorGray200": '--primitive-color-gray-200',
  "primitiveColorGray300": '--primitive-color-gray-300',
  "primitiveColorGray400": '--primitive-color-gray-400',
  "primitiveColorGray500": '--primitive-color-gray-500',
  "primitiveColorGray600": '--primitive-color-gray-600',
  "primitiveColorGray700": '--primitive-color-gray-700',
  "primitiveColorGray800": '--primitive-color-gray-800',
  "primitiveColorGray900": '--primitive-color-gray-900',
  "primitiveColorGray950": '--primitive-color-gray-950',
  "primitiveColorGreen400": '--primitive-color-green-400',
  "primitiveColorGreen600": '--primitive-color-green-600',
  "primitiveColorGreen700": '--primitive-color-green-700',
  "primitiveColorRed400": '--primitive-color-red-400',
  "primitiveColorRed600": '--primitive-color-red-600',
  "primitiveColorRed700": '--primitive-color-red-700',
  "primitiveColorAmber400": '--primitive-color-amber-400',
  "primitiveColorAmber600": '--primitive-color-amber-600',
  "primitiveColorAmber700": '--primitive-color-amber-700',
  "primitiveColorWhite": '--primitive-color-white',
  "primitiveColorBlack": '--primitive-color-black',
  "primitiveColorHcBlue": '--primitive-color-hc-blue',
  "primitiveColorHcYellow": '--primitive-color-hc-yellow',
  "primitiveSpacing0": '--primitive-spacing-0',
  "primitiveSpacing1": '--primitive-spacing-1',
  "primitiveSpacing2": '--primitive-spacing-2',
  "primitiveSpacing3": '--primitive-spacing-3',
  "primitiveSpacing4": '--primitive-spacing-4',
  "primitiveSpacing6": '--primitive-spacing-6',
  "primitiveSpacing8": '--primitive-spacing-8',
  "primitiveSpacing12": '--primitive-spacing-12',
  "primitiveSpacing16": '--primitive-spacing-16',
  "primitiveRadiusNone": '--primitive-radius-none',
  "primitiveRadiusSm": '--primitive-radius-sm',
  "primitiveRadiusMd": '--primitive-radius-md',
  "primitiveRadiusLg": '--primitive-radius-lg',
  "primitiveRadiusFull": '--primitive-radius-full',
  "primitiveFontSizeXs": '--primitive-font-size-xs',
  "primitiveFontSizeSm": '--primitive-font-size-sm',
  "primitiveFontSizeBase": '--primitive-font-size-base',
  "primitiveFontSizeLg": '--primitive-font-size-lg',
  "primitiveFontSizeXl": '--primitive-font-size-xl',
  "primitiveFontSize2xl": '--primitive-font-size-2xl',
  "primitiveFontWeightRegular": '--primitive-font-weight-regular',
  "primitiveFontWeightMedium": '--primitive-font-weight-medium',
  "primitiveFontWeightSemibold": '--primitive-font-weight-semibold',
  "primitiveFontWeightBold": '--primitive-font-weight-bold',
  "primitiveLineHeightTight": '--primitive-line-height-tight',
  "primitiveLineHeightSnug": '--primitive-line-height-snug',
  "primitiveLineHeightNormal": '--primitive-line-height-normal',
  "primitiveLineHeightRelaxed": '--primitive-line-height-relaxed',
  "primitiveBorderWidthNone": '--primitive-border-width-none',
  "primitiveBorderWidthThin": '--primitive-border-width-thin',
  "primitiveBorderWidthThick": '--primitive-border-width-thick',
  "colorTextPrimary": '--color-text-primary',
  "colorTextSecondary": '--color-text-secondary',
  "colorTextDisabled": '--color-text-disabled',
  "colorTextInverse": '--color-text-inverse',
  "colorSurfaceBase": '--color-surface-base',
  "colorSurfaceRaised": '--color-surface-raised',
  "colorSurfaceOverlay": '--color-surface-overlay',
  "colorBorderDefault": '--color-border-default',
  "colorBorderStrong": '--color-border-strong',
  "colorBorderFocus": '--color-border-focus',
  "colorActionPrimary": '--color-action-primary',
  "colorActionPrimaryHover": '--color-action-primary-hover',
  "colorActionPrimaryText": '--color-action-primary-text',
  "colorStatusSuccess": '--color-status-success',
  "colorStatusWarning": '--color-status-warning',
  "colorStatusDanger": '--color-status-danger',
  "colorStatusInfo": '--color-status-info',
  "spacingNone": '--spacing-none',
  "spacingXs": '--spacing-xs',
  "spacingSm": '--spacing-sm',
  "spacingMd": '--spacing-md',
  "spacingLg": '--spacing-lg',
  "spacingXl": '--spacing-xl',
  "spacing2xl": '--spacing-2xl',
  "radiusSm": '--radius-sm',
  "radiusMd": '--radius-md',
  "radiusLg": '--radius-lg',
  "radiusFull": '--radius-full',
  "borderWidth": '--border-width',
  "typographyDisplayFontSize": '--typography-display-font-size',
  "typographyDisplayFontWeight": '--typography-display-font-weight',
  "typographyDisplayLineHeight": '--typography-display-line-height',
  "typographyHeading1FontSize": '--typography-heading1-font-size',
  "typographyHeading1FontWeight": '--typography-heading1-font-weight',
  "typographyHeading1LineHeight": '--typography-heading1-line-height',
  "typographyHeading2FontSize": '--typography-heading2-font-size',
  "typographyHeading2FontWeight": '--typography-heading2-font-weight',
  "typographyHeading2LineHeight": '--typography-heading2-line-height',
  "typographyHeading3FontSize": '--typography-heading3-font-size',
  "typographyHeading3FontWeight": '--typography-heading3-font-weight',
  "typographyHeading3LineHeight": '--typography-heading3-line-height',
  "typographyBodyFontSize": '--typography-body-font-size',
  "typographyBodyFontWeight": '--typography-body-font-weight',
  "typographyBodyLineHeight": '--typography-body-line-height',
  "typographyBodySmallFontSize": '--typography-body-small-font-size',
  "typographyBodySmallFontWeight": '--typography-body-small-font-weight',
  "typographyBodySmallLineHeight": '--typography-body-small-line-height',
  "typographyCaptionFontSize": '--typography-caption-font-size',
  "typographyCaptionFontWeight": '--typography-caption-font-weight',
  "typographyCaptionLineHeight": '--typography-caption-line-height',
  "typographyLabelFontSize": '--typography-label-font-size',
  "typographyLabelFontWeight": '--typography-label-font-weight',
  "typographyLabelLineHeight": '--typography-label-line-height',
  "elevation0": '--elevation-0',
  "elevation1": '--elevation-1',
  "elevation2": '--elevation-2',
  "elevation3": '--elevation-3',
  "motionDurationMicro": '--motion-duration-micro',
  "motionDurationSmall": '--motion-duration-small',
  "motionDurationMedium": '--motion-duration-medium',
  "motionDurationLarge": '--motion-duration-large',
  "motionEasingStandard": '--motion-easing-standard',
  "motionEasingDecelerate": '--motion-easing-decelerate',
  "motionReducedMotionDurationMicro": '--motion-reduced-motion-duration-micro',
  "motionReducedMotionDurationSmall": '--motion-reduced-motion-duration-small',
  "motionReducedMotionDurationMedium": '--motion-reduced-motion-duration-medium',
  "motionReducedMotionDurationLarge": '--motion-reduced-motion-duration-large',
  "opacityDisabled": '--opacity-disabled',
  "opacityOverlay": '--opacity-overlay',
  "opacityHover": '--opacity-hover',
  "zIndexDropdown": '--z-index-dropdown',
  "zIndexSticky": '--z-index-sticky',
  "zIndexDrawer": '--z-index-drawer',
  "zIndexModal": '--z-index-modal',
  "zIndexToast": '--z-index-toast',
  "zIndexTooltip": '--z-index-tooltip',
  "componentButtonPrimaryBackground": '--component-button-primary-background',
  "componentButtonPrimaryBackgroundHover": '--component-button-primary-background-hover',
  "componentButtonPrimaryText": '--component-button-primary-text',
  "componentButtonRadius": '--component-button-radius',
  "componentButtonPaddingX": '--component-button-padding-x',
  "componentButtonPaddingY": '--component-button-padding-y',
  "componentCardPadding": '--component-card-padding',
  "componentCardRadius": '--component-card-radius',
  "componentCardBackground": '--component-card-background',
  "componentCardBorder": '--component-card-border',
  "componentDataGridRowHeight": '--component-data-grid-row-height',
  "componentDataGridHeaderHeight": '--component-data-grid-header-height',
  "componentDataGridCellPaddingX": '--component-data-grid-cell-padding-x',
  "componentDataGridBorderColor": '--component-data-grid-border-color',
  "componentDataGridHeaderBackground": '--component-data-grid-header-background',
  "componentAppShellSidebarWidth": '--component-app-shell-sidebar-width',
  "componentAppShellSidebarCollapsedWidth": '--component-app-shell-sidebar-collapsed-width',
  "componentAppShellTopBarHeight": '--component-app-shell-top-bar-height',
  "componentFocusRingWidth": '--component-focus-ring-width',
  "componentFocusRingColor": '--component-focus-ring-color',
  "componentFocusRingOffset": '--component-focus-ring-offset',
} as const;

export type TokenName = keyof typeof tokenVars;

/**
 * Read a token value at runtime.
 *
 * Only for cases where a token is needed in logic rather than CSS —
 * computing a chart series colour, for example. Styling always goes
 * through the CSS custom property directly.
 */
export function readToken(name: TokenName, element: HTMLElement = document.documentElement): string {
  return getComputedStyle(element).getPropertyValue(tokenVars[name]).trim();
}
